### ISSUE TITLE
Connecting to Local?

### ISSUE THREAD

**Issue by mattvv** [seletskiy/firebase-emulator#1]
Hey @seletskiy 
What did you do to connect to the local docker instance? Did you used the mocked interface from firebase or connect using a normal connection string? (trying to connect from an app in another container)

**Comment by seletskiy** [comment]
Hey @mattvv!

If I understood you correctly, what you want is to connect to firebase-emulator from app running in another container.

> Did you used the mocked interface from firebase or connect using a normal connection string?

You just use whatever firebase client for your language. That's whole point of it.

One important thing to understand here — often firebase clients don't allow to specify URL which you want to connect to and they have hardcoded base URL `.firebaseio.com` in theirs code. You typically specify firebase database name (e.g. `mydb`) and they prepend it to base URL to get target domain (e.g. `mydb.firebaseio.com`)

So, to connect to local firebase instance we need to make sure that some domain like `local.firebaseio.com` resolves into IP address of our locally running firebase container.

They also use HTTPS to communicate with firebase, so we need to have trusted self-signed cert on the machine (or container) where we want to connect to firebase emulator.

To do that you need two things:

1. Link your app container with firebase container.

    Specify `--link` argument this when you start your app container:

    ```
    docker run --link firebase:local.firebaseio.com …
    ```

2. Copy self-signed certificate for `local.firebaseio.com` into app container (from directory where you've built firebase emulator) and update certificates.

    ```
    docker cp nginx.crt <your-app-container>:/usr/local/share/ca-certificates/
    docker exec <your-app-container> update-ca-certificates
    ```
    If you will see warning `WARNING: ca-certificates.crt does not contain exactly one certificate…`, just ignore it.
